version: '3.9'

services:

  poc.api.serilog.net8-webapi:
    ports:
      - 5071:5071
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:gfmaurila
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:gfmaurila
